"use strict";

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert("stories", [
      {
        name: "TỘI ÁI AN CÁCH NHĨ – ÁM DẠ THIÊN",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 50,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        name: "TỘI ÁI",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 40,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 0,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },{
        name: "ÁM DẠ THIÊN",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 40,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 0,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỰ CẨM",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 5,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 10,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "THẦN ĐẠO ĐAN TÔN",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 22,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Quân Lâm Binh Vương",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 24,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Độc Tôn Thiên Hạ",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 6,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 25,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Ông Xã Bạc Tỷ Là Chủ Nợ",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 26,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Cô Vợ Câm Mang Con Bỏ Chạy",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 5,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 27,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Vợ Bất Đắc Dĩ Của Tổng Tài",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Đồ Đệ Xuống Núi Vô Địch Thiên Hạ",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 3,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 40,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Nhạc Tiên Sinh Đang Không Vui",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 31,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Cá Mặn Tiểu Thiếu Gia",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 31,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Chân Long Chí Tôn Đô Thị",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 6,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 29,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Phản Hồi Sau Hôn Nhân",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Đuổi Theo Gió",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 21,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Cưa Nhầm Bạn Trai, Được Chồng Như Ý",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 2,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 43,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Khôn Ninh",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 45,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " VAN's Force: Phế Tích Thế Giới Các Thần",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 52,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Mỹ Thực Gia Ở Dị Giới",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 35,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Tiêu Tổng, Xin Tha Cho Tôi",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 15,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Trúc Mã Vừa Ngọt Lại Mặn",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Trúc Mã Vừa Ngọt Lại Mặn",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 35,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: " Báo Đen",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 15,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỰ CẨM",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "THẦN ĐẠO ĐAN TÔN",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 35,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỘI ÁI AN CÁCH NHĨ – ÁM DẠ THIÊN",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 15,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỰ CẨM",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "THẦN ĐẠO ĐAN TÔN",
        description: `
          Tác giả:Cô Đơn Địa Phi
          Thể loại:Tiên Hiệp, Huyền Huyễn
          Nguồn:Phong Nguyệt Lâu
          Trạng thái:Đang ra
          1 2 3 4 5 6 7 8 9 10
          Đánh giá: 6.9/10 từ 8105 lượt
          Lăng Hàn - Một Đan Đế đại danh đỉnh định mang trong thân mình tuyệt thế công pháp vì truy cầu bước cuối, xé bỏ tấm màn thành thần nhưng thất bại đã phải bỏ mình. Thế nhưng ông trời dường như không muốn tuyệt dường người, Lăng Hàn đã được trọng sinh vào một thiếu niên cùng tên và điều may mắn nhất là "Bất Diệt Thiên Kinh" ấn ký vẫn còn nằm nguyên trong tâm thức hắn.
          
          Từ nay về sau sóng gió cuộn trào nổi lên, Đan Đế ngày xưa bây giờ phải cùng tranh phong với vô số thiên tài trẻ tuổi, lại bắt đầu một truyền thuyết mới như để chứng minh với trời đất: Ta, là người mạnh nhất!`,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 35,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỘI ÁI AN CÁCH NHĨ – ÁM DẠ THIÊN",
        description:
          "Là câu chuyện về chó hoang bị vứt bỏ cùng trinh thám kiêm nghệ thuật gia đã thu nhận con chó hoang đó",
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 15,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "TỰ CẨM",
        description: `Trong kinh thành mọi người đều đồn đại rằng ở trong Khương gia thì Tứ tiểu thư nổi tiếng là một đại tuyệt sắc mỹ nhân. Nhưng đáng tiếc là đáng tiếc lúc nàng xinh đẹp nhất lại bị phủ An quốc công chọn trúng.
          Không chỉ vậy mà đêm trước khi Khương Tự xuất giá, vị hôn phu cùng nữ nhân khác nhảy sông tự tử `,
        total_chapper: 4,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 0,
        image: `image44.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // truyện tranh
      {
        name: "Trọng Sinh Trở Lại: Sủng Nịch Độc Nhất Vô Nhị",
        description: `Trùng sinh và quay lại tuổi 17, Vân Tưởng Tưởng thề sẽ không bị bắt nạt lần nữa, cô đánh vào mặt tên tra nam, lên giọng tìm kiếm bạn đời trăm năm, nhưng bị ép phải chấp nhận một người đàn ông bị tật ở chân, Vân Tưởng Tưởng bị cười nhạo, bị châm biếm. Nhưng người đàn ông giữ cô ấy trong lòng bàn tay của mình, người xúc phạm cô ấy, bị trả giá 10 lần, người đã lừa dối cô ấy, trả giá gấp trăm lần. Một ngày nọ, Vân Tưởng Tưởng bị sốc: “Anh có thể đi được ư? “Người đàn ông vẻ mặt vô tội:” Tôi chưa bao giờ nói rằng tôi không thể đi được.”`,
        total_chapper: 10,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `trongsinhtrolai.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Kết Thúc Của Nhân Vật Phản Diện Chỉ Có Thể Là Cái Chết",
        description: `Penelope Eckart được tái sinh thành con gái nuôi của Công tước Eckart và là nữ nhân vật phản diện của một trò chơi hẹn hò harem ngược. Vấn đề là, khi cô ấy bước vào trò chơi với độ khó cao nhất, và dù cô ấy có làm gì đi chăng nữa, cái chết vẫn chờ cô ấy ở mọi kết thúc! Trước khi “con gái thực sự” của Công tước Eckart xuất hiện, cô phải chọn một trong những nam chính và đạt được kết thúc có hậu để sống sót. Nhưng hai anh em như những hoàng tử điên cuồng, luôn gây chiến với cô ấy từ mọi điều nhỏ nhặt, nơi  mọi con đường dẫn đến cái chết. Thậm chí truyện còn xoay quanh một pháp sư say mê nữ chính, và một hiệp sĩ nô lệ trung thành! Nhưng bằng cách nào đó, mức độ yêu thích của những nam chính càng tăng khi cô đi quá giới hạn với họ!   Đây là câu chuyện sinh tồn của Penelope, cô gái bị vướng vào một cuộc hẹn hò điên rồ với câu chuyện harem ngược!`,
        total_chapper: 8,
        author: "Gwon GyeoulSuol",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `ketthucuanhanvatphandien.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vạn Cổ Tối Cường Tông",
        description: `Truyện tranh Vạn Cổ Tối Cường Tông được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Vạn Cổ Tối Cường Tông.`,
        total_chapper: 18,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 50,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Đại Tượng Vô Hình",
        description: `Nữ chính trong một lần tai nạn xe bị sinh vật bí ẩn gá vào người, sau khi tỉnh lại đến một thế giới yêu linh. Trong lúc cô ấy sợ hãi, tuyệt vọng thì xuất hiện một thiếu niên cứu cô ta về hiện thế. Thì ra thế giới này có yêu linh, sinh vật trong cơ thể cô ta là yêu linh tên "Nhân Tiêu", không cách nào đẩy yêu linh ra ngoài được, cùng đồng hành trên con đường trừ yêu...`,
        total_chapper: 18,
        author: "Phan Kỳ Động Mạn",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Komi không thể giao tiếp",
        description: `Tên khác: Komi-san can't speak well.; Komi-san has a communication disease.; Komi-san has poor communication skills.; Komi-san is asocial.; Komi-san is socially ill Một em dở giao tiếp, nhưng 1 khi đã nói thì.......`,
        total_chapper: 18,
        author: "Tomohito Oda",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `komikhongthegiaotiep.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Trọng Sinh Trở Lại: Sủng Nịch Độc Nhất Vô Nhị",
        description: `Trùng sinh và quay lại tuổi 17, Vân Tưởng Tưởng thề sẽ không bị bắt nạt lần nữa, cô đánh vào mặt tên tra nam, lên giọng tìm kiếm bạn đời trăm năm, nhưng bị ép phải chấp nhận một người đàn ông bị tật ở chân, Vân Tưởng Tưởng bị cười nhạo, bị châm biếm. Nhưng người đàn ông giữ cô ấy trong lòng bàn tay của mình, người xúc phạm cô ấy, bị trả giá 10 lần, người đã lừa dối cô ấy, trả giá gấp trăm lần. Một ngày nọ, Vân Tưởng Tưởng bị sốc: “Anh có thể đi được ư? “Người đàn ông vẻ mặt vô tội:” Tôi chưa bao giờ nói rằng tôi không thể đi được.”`,
        total_chapper: 10,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `trongsinhtrolai.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Kết Thúc Của Nhân Vật Phản Diện Chỉ Có Thể Là Cái Chết",
        description: `Penelope Eckart được tái sinh thành con gái nuôi của Công tước Eckart và là nữ nhân vật phản diện của một trò chơi hẹn hò harem ngược. Vấn đề là, khi cô ấy bước vào trò chơi với độ khó cao nhất, và dù cô ấy có làm gì đi chăng nữa, cái chết vẫn chờ cô ấy ở mọi kết thúc! Trước khi “con gái thực sự” của Công tước Eckart xuất hiện, cô phải chọn một trong những nam chính và đạt được kết thúc có hậu để sống sót. Nhưng hai anh em như những hoàng tử điên cuồng, luôn gây chiến với cô ấy từ mọi điều nhỏ nhặt, nơi  mọi con đường dẫn đến cái chết. Thậm chí truyện còn xoay quanh một pháp sư say mê nữ chính, và một hiệp sĩ nô lệ trung thành! Nhưng bằng cách nào đó, mức độ yêu thích của những nam chính càng tăng khi cô đi quá giới hạn với họ!   Đây là câu chuyện sinh tồn của Penelope, cô gái bị vướng vào một cuộc hẹn hò điên rồ với câu chuyện harem ngược!`,
        total_chapper: 8,
        author: "Gwon GyeoulSuol",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `ketthucuanhanvatphandien.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vạn Cổ Tối Cường Tông",
        description: `Truyện tranh Vạn Cổ Tối Cường Tông được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Vạn Cổ Tối Cường Tông.`,
        total_chapper: 18,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 50,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Đại Tượng Vô Hình",
        description: `Nữ chính trong một lần tai nạn xe bị sinh vật bí ẩn gá vào người, sau khi tỉnh lại đến một thế giới yêu linh. Trong lúc cô ấy sợ hãi, tuyệt vọng thì xuất hiện một thiếu niên cứu cô ta về hiện thế. Thì ra thế giới này có yêu linh, sinh vật trong cơ thể cô ta là yêu linh tên "Nhân Tiêu", không cách nào đẩy yêu linh ra ngoài được, cùng đồng hành trên con đường trừ yêu...`,
        total_chapper: 18,
        author: "Phan Kỳ Động Mạn",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Komi không thể giao tiếp",
        description: `Tên khác: Komi-san can't speak well.; Komi-san has a communication disease.; Komi-san has poor communication skills.; Komi-san is asocial.; Komi-san is socially ill Một em dở giao tiếp, nhưng 1 khi đã nói thì.......`,
        total_chapper: 18,
        author: "Tomohito Oda",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `komikhongthegiaotiep.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Trọng Sinh Trở Lại: Sủng Nịch Độc Nhất Vô Nhị",
        description: `Trùng sinh và quay lại tuổi 17, Vân Tưởng Tưởng thề sẽ không bị bắt nạt lần nữa, cô đánh vào mặt tên tra nam, lên giọng tìm kiếm bạn đời trăm năm, nhưng bị ép phải chấp nhận một người đàn ông bị tật ở chân, Vân Tưởng Tưởng bị cười nhạo, bị châm biếm. Nhưng người đàn ông giữ cô ấy trong lòng bàn tay của mình, người xúc phạm cô ấy, bị trả giá 10 lần, người đã lừa dối cô ấy, trả giá gấp trăm lần. Một ngày nọ, Vân Tưởng Tưởng bị sốc: “Anh có thể đi được ư? “Người đàn ông vẻ mặt vô tội:” Tôi chưa bao giờ nói rằng tôi không thể đi được.”`,
        total_chapper: 10,
        author: "Nhĩ Nhã",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `trongsinhtrolai.png`,
        view: 33,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Kết Thúc Của Nhân Vật Phản Diện Chỉ Có Thể Là Cái Chết",
        description: `Penelope Eckart được tái sinh thành con gái nuôi của Công tước Eckart và là nữ nhân vật phản diện của một trò chơi hẹn hò harem ngược. Vấn đề là, khi cô ấy bước vào trò chơi với độ khó cao nhất, và dù cô ấy có làm gì đi chăng nữa, cái chết vẫn chờ cô ấy ở mọi kết thúc! Trước khi “con gái thực sự” của Công tước Eckart xuất hiện, cô phải chọn một trong những nam chính và đạt được kết thúc có hậu để sống sót. Nhưng hai anh em như những hoàng tử điên cuồng, luôn gây chiến với cô ấy từ mọi điều nhỏ nhặt, nơi  mọi con đường dẫn đến cái chết. Thậm chí truyện còn xoay quanh một pháp sư say mê nữ chính, và một hiệp sĩ nô lệ trung thành! Nhưng bằng cách nào đó, mức độ yêu thích của những nam chính càng tăng khi cô đi quá giới hạn với họ!   Đây là câu chuyện sinh tồn của Penelope, cô gái bị vướng vào một cuộc hẹn hò điên rồ với câu chuyện harem ngược!`,
        total_chapper: 8,
        author: "Gwon GyeoulSuol",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `ketthucuanhanvatphandien.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Người Nuôi Rồng",
        description: `Truyện tranh Người Nuôi Rồng được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Người Nuôi Rồng.`,
        total_chapper: 8,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `nguoinuoirong.png`,
        view: 30,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Vạn Cổ Tối Cường Tông",
        description: `Truyện tranh Vạn Cổ Tối Cường Tông được cập nhật nhanh và đầy đủ nhất tại NetTruyen. Bạn đọc đừng quên để lại bình luận và chia sẻ, ủng hộ NetTruyen ra các chương mới nhất của truyện Vạn Cổ Tối Cường Tông.`,
        total_chapper: 18,
        author: "Đang cập nhật",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 50,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        name: "Đại Tượng Vô Hình",
        description: `Nữ chính trong một lần tai nạn xe bị sinh vật bí ẩn gá vào người, sau khi tỉnh lại đến một thế giới yêu linh. Trong lúc cô ấy sợ hãi, tuyệt vọng thì xuất hiện một thiếu niên cứu cô ta về hiện thế. Thì ra thế giới này có yêu linh, sinh vật trong cơ thể cô ta là yêu linh tên "Nhân Tiêu", không cách nào đẩy yêu linh ra ngoài được, cùng đồng hành trên con đường trừ yêu...`,
        total_chapper: 18,
        author: "Phan Kỳ Động Mạn",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `vancotoicuongtong.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },  
      {
        name: "Komi không thể giao tiếp",
        description: `Tên khác: Komi-san can't speak well.; Komi-san has a communication disease.; Komi-san has poor communication skills.; Komi-san is asocial.; Komi-san is socially ill Một em dở giao tiếp, nhưng 1 khi đã nói thì.......`,
        total_chapper: 18,
        author: "Tomohito Oda",
        status_approve: true,
        status_chapter: false,
        classifi: 1,
        image: `komikhongthegiaotiep.png`,
        view: 150,
        id_user: 2,
        deleted: 0,
         version: 0,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
     
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete("stories", null, {});
  },
};
