export {default as Footer } from './Footer';
export {default as Header } from './Header';
export {default as Setup } from './Setup';
export {default as Search } from './Search';
export {default as ContentHome } from './Story/ContentHome';
export {default as ListType } from './ListType';
export {default as StoryUpdating } from './Story/StoryUpdating';
export {default as Comments } from './Comment/Comments';
export {default as FormComment } from './Comment/FormComment';