export {default as HomeAdmin} from './HomeAdmin'
export {default as ListStoryAdmin} from './ListStoryAdmin'
export {default as ListCategoryAdmin} from './ListCategoryAdmin'
export {default as ListPendingAdmin} from './ListPendingAdmin'
export {default as ListUserAdmin} from './ListUserAdmin'
export {default as DetailStoryAdmin} from './DetailStoryAdmin'
export {default as PendingDetailAdmin} from './PendingDetailAdmin'