const actionTypes = {
    GET_HOME:'GET_HOME',
    GET_STORIES_FOR_ADMIN:'GET_STORIES_FOR_ADMIN',
    GET_STORIES_APPROVED_FOR_ADMIN:'GET_STORIES_APPROVED_FOR_ADMIN',
    GET_STORIES_PENDING_FOR_ADMIN:'GET_STORIES_PENDING_FOR_ADMIN',
    GET_STORY_DETAIL_ADMIN:'GET_STORY_DETAIL_ADMIN',
    GET_CATEGORIES_FOR_ADMIN:'GET_CATEGORIES_FOR_ADMIN',
    GET_USER_ID_ADMIN:'GET_USER_ID_ADMIN',
    GET_USER_FOR_ADMIN:'GET_USER_FOR_ADMIN',

}

export default actionTypes