const actionTypes = {
    GET_HOME:'GET_HOME',
    GET_CATEGORIES_FOR_POSTER:'GET_CATEGORIES_FOR_POSTER',
    GET_STORIES_FOR_POSTER:'GET_STORIES_FOR_POSTER',
    GET_STORY_DETAIL:'GET_STORY_DETAIL',

    // sdjf0ẻu
    GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
    GET_CATEGORIES_FAILURE: 'GET_CATEGORIES_FAILURE',
    GET_STORIES_FOR_ADMIN:'GET_STORIES_FOR_ADMIN',
    GET_STORIES_APPROVED_FOR_ADMIN:'GET_STORIES_APPROVED_FOR_ADMIN',
    GET_STORIES_PENDING_FOR_ADMIN:'GET_STORIES_PENDING_FOR_ADMIN',
    GET_STORY_DETAIL_ADMIN:'GET_STORY_DETAIL_ADMIN',
    GET_CATEGORIES_FOR_ADMIN:'GET_CATEGORIES_FOR_ADMIN',
    GET_USER_ID_ADMIN:'GET_USER_ID_ADMIN',
    GET_USER_FOR_ADMIN:'GET_USER_FOR_ADMIN',

    
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  SET_USER_ROLE: 'SET_USER_ROLE',
  REGISTER_SUCCESS:'REGISTER_SUCCESS',

}

export default actionTypes
